### ISSUE TITLE
Can this be used as a drop-in replacement for Flask-Mail?

### ISSUE THREAD

**Issue by torotil** [vitalk/flask-mailer#17]
Can this be used as a drop-in replacement for Flask-Mail? This would be especially nice for users of Flask-Security.

**Comment by vitalk** [comment]
Hi @torotil!

Sadly, but not. Now extension missed some core features:
- attachments support,
- html body,
- signals.

I planned to add them in next two month. For now the Flask-Mail is a best choice.
